import { BaseSkill, SkillResult, ExecutionContext, makeSuccessResult, makeErrorResult } from './base-skill';
import { TaskFile } from '../models/task-file';
import fs from 'fs';
import path from 'path';

export class DraftEmailSkill implements BaseSkill {
  name = 'DraftEmailSkill';

  canHandle(task: TaskFile): boolean {
    const lower = task.body.toLowerCase();
    return lower.includes('email') || lower.includes('draft') || lower.includes('compose');
  }

  async execute(task: TaskFile, context: ExecutionContext): Promise<SkillResult> {
    context.logger.info('skill_execute', `${this.name}: Drafting email for ${task.filename}`, task.filename);

    const prompt = `You are an AI Employee. Draft a professional email based on the following request.

## Request
${task.body}

Provide the email in this format:
Subject: <subject>
To: <recipient if specified, or [RECIPIENT]>

<email body>

Note: This is a DRAFT only. It will NOT be sent without human approval.`;

    const response = await context.claudeClient.executeSkill(prompt);

    if (!response.success) {
      return makeErrorResult(response.error || 'Email draft failed');
    }

    // Save draft to vault
    const draftFilename = `DRAFT_${path.basename(task.filename)}`;
    const draftPath = path.join(context.vaultRoot, 'Plans', draftFilename);

    if (!context.dryRun) {
      fs.writeFileSync(draftPath, `# Email Draft\n\n${response.text}\n\n---\n*Draft generated by AI Employee. Review before sending.*\n`, 'utf-8');
    }

    return makeSuccessResult(response.text, [draftPath]);
  }
}
